### ISSUE TITLE
feat(markdown): Markdown; MarkdownSection; CodeBlock components [3h]

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/planetar#13]
need `<Markdown />`; `<MarkdownSection />`; `<CodeBlock />` components

### initial steps

- [x] `npm run dep:install`
- [x] create a new package under `packages/markdown`
- [x] copy all the boiler plate of `packages/atoms` but delete all components and add 3 new components: `Markdown.vue`; `MarkdownSection.vue`; `CodeBlock.vue`.
- [x] make sure the `index.js` and `package.json` files are adjusted (we don't need a build step for now, the npm module can be exposed directly from the source files without compilation)
- [x] the "name" in `package.json` should be `@planetar/markdown`
- [x] add the package to the `dev` project so you can develop: `lerna add @planetar/markdown --scope dev`
- [x] `npm run dev`
- [x] make a dev page for in the dev project for each of the new components below (check other examples when you open the dev server)

### Markdown component

I want to swap out [this line](https://github.com/mesqueeb/planetar/blob/production/packages/example-card/src/components/ExampleSection.vue#L4) with `<Markdown />`

- [x] base implementation on the line mentioned above from `ExampleSection.vue`
- [x] use `<slot>{ content }</slot>` so both the default slot and a prop called `content` can be used to render the markdown.
- [x] Add a dev page with an example of the `<Markdown />` component (`npm run dev`)

### MarkdownSection component

MarkdownSection will just be a wrapper for `<MarkDown />` but accept a `filePath` instead (just like `ExampleSection`).

- [x] have a `filePath` as only prop
- [x] `filePath` must point to a markdown file
- [x] implement something like:
```js
import { dynamicImport } from '@planetar/utils'
// and on created
dynamicImport(filePath, 'md', 'string')
  .then(markdownContent => doSomething(markdownContent))
```
- [x] for this implementation we need to add 'md' as possibility to the dynamicImport function
- [x] 'md' should only use the rawLoader and therefore the last param has to be `'string'` or else an error is to be thrown
- [x] Add a dev page with an example of the `<MarkdownSection />` component (`npm run dev`)

### CodeBlock component

I want to swap out [this part](https://github.com/mesqueeb/planetar/blob/production/packages/example-card/src/components/ExampleCard.vue#L11~L16) with `<CodeBlock />`

- [x] I think by now you can guess what this should do and how to implement it : )
- [x] feel free to choose appropriate prop names
- [x] Add a dev page with 3 examples of the `<CodeBlock />` component - one for JS, one for HTML, one for CSS

### finally

- [x] expose all three components at `packages/planetar`

**Comment by AndrewKoch** [comment]
Draft PR is here: https://github.com/CyCraft/planetar/pull/17

This work is ready for review, but I will keep adding work to this branch for other tickets with related tasks.
