### ISSUE TITLE
fix(markdown): make `<br />` show up

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/planetar#16]
<img width="591" alt="Screenshot 2020-08-27 at 19 58 25" src="https://user-images.githubusercontent.com/3253920/91434529-e2c18980-e89f-11ea-8e5c-96872cbff084.png">

**Comment by AndrewKoch** [comment]
this was fixed with this commit: https://github.com/CyCraft/planetar/commit/f4b160318f0ba7fa0779db438127b4b0ef82f3ee

also, i made the same changes to the `example-card` helper functions
